Changed CRLF to LF.  (Some, but not all line endings were CRLF since bkc's checkin.)
There's also a bug here: I ran this with rates.py output from a
previous version and it said

UnboundLocalError: local variable 'hamdevall' referenced before
assignment

But I don't know what value to initialize it (and spamdevall) to.